// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Configuration;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Entity.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("BUYER_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("END_DATE");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FINAL_PRICE");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.ToTable("AUCTIONS");
                });

            modelBuilder.Entity("Model.Entity.AuctionCategorie", b =>
                {
                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<string>("Label")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CATEGORIE");

                    b.HasKey("AuctionId", "Label");

                    b.HasIndex("Label");

                    b.ToTable("AUCTION_HAS_CATEGORIES");
                });

            modelBuilder.Entity("Model.Entity.AuctionImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IMAGE_ID");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("IMAGE");

                    b.HasKey("ImageId");

                    b.HasIndex("AuctionId");

                    b.ToTable("AUCTION_IMAGES");
                });

            modelBuilder.Entity("Model.Entity.BiddingAuctionBid", b =>
                {
                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BID_DATE");

                    b.Property<int>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("BIDDER_ID");

                    b.HasKey("AuctionId", "Price");

                    b.HasIndex("BidderId");

                    b.ToTable("BIDDING_AUCTION_BIDS");
                });

            modelBuilder.Entity("Model.Entity.Categorie", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LABEL");

                    b.HasKey("Label");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("Model.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("BALANCE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob")
                        .HasColumnName("IMAGE");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Model.Entity.Admin", b =>
                {
                    b.HasBaseType("Model.Entity.User");

                    b.ToTable("ADMINS");
                });

            modelBuilder.Entity("Model.Entity.BiddingAuction", b =>
                {
                    b.HasBaseType("Model.Entity.Auction");

                    b.Property<decimal?>("InstantBuyPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("INSTANT_BUY_PRICE");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("STARTING_PRICE");

                    b.Property<decimal?>("Step")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("STEP");

                    b.ToTable("BIDDING_AUCTION");
                });

            modelBuilder.Entity("Model.Entity.BuyAuction", b =>
                {
                    b.HasBaseType("Model.Entity.Auction");

                    b.Property<decimal>("MinimumPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MINIMUM_PRICE");

                    b.ToTable("BUY_AUCTION");
                });

            modelBuilder.Entity("Model.Entity.Auction", b =>
                {
                    b.HasOne("Model.Entity.User", "Buyer")
                        .WithMany("Buys")
                        .HasForeignKey("BuyerId");

                    b.HasOne("Model.Entity.User", "Seller")
                        .WithMany("Sells")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Model.Entity.AuctionCategorie", b =>
                {
                    b.HasOne("Model.Entity.Auction", "Auction")
                        .WithMany("Categories")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Categorie", "Categorie")
                        .WithMany("Auctions")
                        .HasForeignKey("Label")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Model.Entity.AuctionImage", b =>
                {
                    b.HasOne("Model.Entity.Auction", "Auction")
                        .WithMany("Images")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Model.Entity.BiddingAuctionBid", b =>
                {
                    b.HasOne("Model.Entity.BiddingAuction", "Auction")
                        .WithMany("Bidders")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("Model.Entity.Admin", b =>
                {
                    b.HasOne("Model.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Model.Entity.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entity.BiddingAuction", b =>
                {
                    b.HasOne("Model.Entity.Auction", null)
                        .WithOne()
                        .HasForeignKey("Model.Entity.BiddingAuction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entity.BuyAuction", b =>
                {
                    b.HasOne("Model.Entity.Auction", null)
                        .WithOne()
                        .HasForeignKey("Model.Entity.BuyAuction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entity.Auction", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Model.Entity.Categorie", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("Model.Entity.User", b =>
                {
                    b.Navigation("Buys");

                    b.Navigation("Sells");
                });

            modelBuilder.Entity("Model.Entity.BiddingAuction", b =>
                {
                    b.Navigation("Bidders");
                });
#pragma warning restore 612, 618
        }
    }
}
